(()=>{'use strict';
const app=document.querySelector('#app'),voice=document.querySelector('#voice'),sound=document.querySelector('#sound'),chapter=document.querySelector('#chapter');
let stage='intro',narration=false,found=new Set(),matched=new Set(),opened=[],busy=false,matchTimer=null,session=0,angles=[90,180,270],chosen=[],solved=[false,false,false];
const symbols=['☾','✧','☀','✧','☾','☀'],names=['Moon','Star','Sun','Star','Moon','Sun'];
const words=['Courage','Curiosity','Hope','Patience','Kindness','Trust'];
const coords=[[22,58],[39,24],[65,38],[78,70],[48,80]];
const messages=[['A light for your curiosity','I love that there are still things for you to discover. You are allowed to ask questions, change your mind, and be a beginner.'],['A light for being you','Hind, you do not have to turn every moment into an achievement. I hope this little place gives you a moment to simply enjoy yourself.'],['A light from my side of the sky','Somewhere beneath the same sky, I am thinking of you with love and making dua for the good that is still ahead of you.']];
function status(t){let e=document.querySelector('#status');if(e)e.textContent=t;}
function play(){voice.pause();voice.src='assets/stars-'+(stage==='intro'?'welcome':'letter')+'.mp3';voice.play().catch(()=>{narration=false;updateSound();const e=document.querySelector('#audio-state');if(e)e.textContent='Tap “Listen” to try again. The letter is also here to read.';});}
function updateSound(){sound.textContent=narration?'Narration on':'Narration off';sound.setAttribute('aria-pressed',String(narration));}
sound.addEventListener('click',()=>{narration=!narration;updateSound();if(!narration)voice.pause();else if(['intro','letter'].includes(stage))play();else status('Narration is ready for your letter at the end. Enjoy exploring at your own pace.');});
voice.addEventListener('error',()=>{const e=document.querySelector('#audio-state');if(e)e.textContent='The voice could not load. You can still read the message on this page.';});
document.addEventListener('visibilitychange',()=>{if(document.hidden){voice.pause();narration=false;updateSound();}});
function button(label,action,cls='primary'){return `<button class="${cls}" data-action="${action}">${label}</button>`;}
function go(next){voice.pause();clearTimeout(matchTimer);session++;busy=false;opened=[];stage=next;render();app.querySelector('h1,h2')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});if(narration&&['intro','letter'].includes(stage))play();}
function dots(i){return '<div class="stepdots" aria-label="Puzzle '+(i+1)+' of 3">'+[0,1,2].map(n=>`<i class="${n<=i?'on':''}"></i>`).join('')+'</div>';}
function puzzleCopy(i,title,body){return `<div>${dots(i)}<p class="eyebrow">A SMALL DISCOVERY / 0${i+1}</p><h2 tabindex="-1">${title}</h2><p>${body}</p><p class="tiny">Take your time. Hints and another try are always here.</p><div class="skip">${button('A little hint','hint','text-btn')}${button('Show me gently','show','text-btn')}</div><p class="status" id="status" role="status"></p><div class="actions" id="continue"></div></div>`;}
function unlock(i,text){solved[i]=true;status(text);document.querySelector('#continue').innerHTML=button(i===2?'Make my constellation':'Next discovery',i===0?'pattern':i===1?'align':'create');}
function sky(){let path=chosen.map((_,i)=>(i?'L':'M')+coords[i][0]+' '+coords[i][1]).join(' ');return `<div class="skyboard" aria-label="Your constellation with ${chosen.length} stars"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="${path}"/></svg>${chosen.length?chosen.map((w,i)=>`<div class="chosen-star" style="left:${coords[i][0]}%;top:${coords[i][1]}%"><b aria-hidden="true">✦</b><span>${w}</span></div>`).join(''):'<div class="board-empty">Choose a few lights.<br>This sky is yours.</div>'}</div>`;}
function render(){
document.body.classList.toggle('lit',['reveal','letter','end'].includes(stage));app.className='fadein';
chapter.textContent=({intro:'A LITTLE ADVENTURE, JUST FOR YOU',explore:'01 / FIND THE LIGHTS',match:'02 / DISCOVER',pattern:'02 / DISCOVER',align:'02 / DISCOVER',create:'03 / MAKE YOUR SKY',reveal:'A SKY, BROUGHT TO LIFE BY YOU',letter:'A LETTER BENEATH THE STARS',end:'TAKE A LITTLE LIGHT WITH YOU'})[stage];
if(stage==='intro')app.innerHTML=`<section class="intro"><p class="seal" aria-hidden="true">✧</p><p class="eyebrow">DAY FOUR · YOUR LITTLE UNIVERSE</p><h1 tabindex="-1">The night you<br>bring back<br><em>the stars.</em></h1><p class="lead">Hind, I made you a little corner of the night.<br>A place to explore, discover, and remember what you can do.</p><div class="actions">${button('Open the observatory','explore')}${button('Listen to the welcome','listen','quiet')}</div><p class="tiny">A gentle adventure · no clock · go at your own pace</p><p id="audio-state" class="audio-state" role="status"></p></section>`;
if(stage==='explore')app.innerHTML=`<section class="split"><div><p class="eyebrow">WELCOME INSIDE, MY LOVE</p><h2 tabindex="-1">There is light<br>waiting for you.</h2><p>Explore the three glowing objects. Each one has a small message I left here for you.</p><div class="message-box" id="discovery" role="status"><p>Where will you look first?</p></div><div class="actions">${button('Explore the puzzles','match')}</div><p class="tiny">You can revisit any light before moving on.</p></div><div class="explore"><div class="arc" aria-hidden="true"></div>${['The atlas','The dome','The telescope'].map((t,i)=>`<button class="hotspot ${found.has(i)?'found':''}" data-light="${i}" aria-label="Open ${t}">${['☾','✧','⌁'][i]}<span>${t}</span></button>`).join('')}</div></section>`;
if(stage==='match'){app.innerHTML=`<section class="split">${puzzleCopy(0,'Find what belongs together.','Turn over the cards and find the three matching pairs. You can look as many times as you like.')}<div class="panel puzzle-area"><div class="cards">${symbols.map((s,i)=>`<button class="card ${matched.has(i)?'matched':''}" data-card="${i}" aria-label="${matched.has(i)?names[i]+' matched':'Turn card '+(i+1)}" ${matched.has(i)?'disabled':''}>${matched.has(i)?s:'✦'}<span class="caption">${matched.has(i)?'Found':'Explore'}</span></button>`).join('')}</div><p class="tiny">Sometimes recognition comes on the second look.</p></div></section>`;if(solved[0])unlock(0,'You found the connections. Looking again is part of figuring things out.');}
if(stage==='pattern'){app.innerHTML=`<section class="split">${puzzleCopy(1,'Notice one small pattern.','These little moons follow a repeating rhythm. Which shape comes next?')}<div class="panel puzzle-area"><div class="sequence" aria-label="Moon, star, moon, star, moon, missing shape"><span>☾</span><span>✧</span><span>☾</span><span>✧</span><span>☾</span><span>?</span></div><div class="answers"><button data-answer="moon">☾<small>Moon</small></button><button data-answer="star">✧<small>Star</small></button><button data-answer="sun">☀<small>Sun</small></button></div><p class="tiny">Follow the rhythm. You do not have to rush it.</p></div></section>`;if(solved[1])unlock(1,'Moon, star. Moon, star. You noticed the rhythm, one piece at a time.');}
if(stage==='align'){app.innerHTML=`<section class="split">${puzzleCopy(2,'Bring the telescope into focus.','Turn each dial until its gold diamond meets the faint star at the top. Small adjustments can make things clearer.')}<div class="panel puzzle-area"><div class="orbit-set">${angles.map((a,i)=>`<div class="orbit-wrap"><div class="orbit" aria-hidden="true"><div class="pointer" id="pointer${i}" style="transform:rotate(${a}deg)"><span>◆</span></div></div><button data-dial="${i}" aria-label="Turn dial ${i+1} one quarter turn">Turn dial ${i+1}</button><small id="dialstate${i}" aria-live="polite">${a%360===0?'In focus':'Keep exploring'}</small></div>`).join('')}</div><p class="tiny">Each tap moves a diamond one quarter turn clockwise.</p></div></section>`;if(solved[2])unlock(2,'There it is. A little adjustment, another look, and things become clearer.');}
if(stage==='create')app.innerHTML=`<section class="split"><div><p class="eyebrow">A CONSTELLATION THAT BELONGS TO YOU</p><h2 tabindex="-1">What will you<br>carry with you?</h2><p>Choose three to five lights you would like beside you. You do not have to feel them all right now.</p><div class="star-picks">${words.map(w=>`<button data-word="${w}" aria-pressed="${chosen.includes(w)}"><span aria-hidden="true">${chosen.includes(w)?'✦':'✧'}</span>${w}</button>`).join('')}</div><p class="status" id="status" role="status">${chosen.length} ${chosen.length===1?'light':'lights'} chosen. ${chosen.length<3?'Choose at least three.':'Your sky is ready.'}</p><div class="actions"><button class="primary" data-action="reveal" ${chosen.length<3?'disabled':''}>Light up my sky</button></div></div><div id="sky">${sky()}</div></section>`;
if(stage==='reveal')app.innerHTML=`<section class="finale celebrate"><p class="eyebrow">LOOK WHAT YOU BROUGHT TO LIFE</p><h1 tabindex="-1">One small light.<br>Then <em>another.</em></h1>${sky()}<p>Hind, you found your way one small step at a time.<br>You can do that again.</p><div class="actions">${button('There is a letter for me','letter')}</div></section>`;
if(stage==='letter')app.innerHTML=`<article class="panel letter"><p class="eyebrow">FROM MY SIDE OF THE SKY TO YOURS</p><h2 tabindex="-1">My beloved Hind,</h2><div class="actions">${button('Listen to your letter','listen','quiet')}</div><p id="audio-state" class="audio-state" role="status"></p><p>Look at the sky you made. You began with a few scattered lights, and you gave them a shape of your own. I hope you carry a little of that feeling back with you.</p><p>When something seems unfamiliar, it can become familiar. When one approach doesn’t help, you can try another. And when you need a little guidance, you are still the one learning.</p><p>I believe in the mind that asks questions, the courage that tries again, and the gentleness you deserve while you grow. You don’t have to feel confident every minute to take your next step. You can feel unsure and still discover something. You can rest and return. You can understand more tomorrow than you understand tonight.</p><p>And my love for you isn’t waiting at the end of an exam result. It’s here, with you, in this ordinary moment.</p><p>May Allah bring ease to your heart, clarity to what you study, and goodness to every sincere effort you make. May He help you remember what you have learned and approach what comes next with courage. Ameen.</p><p>Whenever you look up tonight, remember that somewhere beneath this same sky, I am making dua for you.</p><p>One small step, my love. Then another.<br><strong>You can learn. You can figure things out. You can do this.</strong></p><p class="signature">With love, always,<br>Musfiqur</p><div class="actions">${button('I can figure things out','end')}</div></article>`;
if(stage==='end')app.innerHTML=`<section class="finale"><p class="eyebrow">YOUR LIGHT GOES WITH YOU</p><h1 tabindex="-1">I can learn.<br>I can try again.<br><em>I can do this.</em></h1><div class="glow-line"></div><p>Whatever your next small step is, let it be yours.<br>I’m cheering for you, Hind. Always.</p>${sky()}<div class="actions">${button('Visit my sky again','reveal','quiet')}${button('Begin another visit','restart','text-btn')}</div></section>`;
}
function turnCard(i){if(busy||matched.has(i)||opened.includes(i)||solved[0])return;const el=app.querySelector(`[data-card="${i}"]`);el.innerHTML=symbols[i]+'<span class="caption">'+names[i]+'</span>';el.setAttribute('aria-label',names[i]);opened.push(i);if(opened.length!==2)return;const [a,b]=opened;if(symbols[a]===symbols[b]){matched.add(a);matched.add(b);opened=[];for(const n of [a,b]){const c=app.querySelector(`[data-card="${n}"]`);c.disabled=true;c.classList.add('matched');c.setAttribute('aria-label',names[n]+' matched');}if(matched.size===6)unlock(0,'You found the connections. Looking again is part of figuring things out.');else status('A pair found. Take your time with the next one.');}else{busy=true;status('Two different lights. Now you know where they are.');const token=session;matchTimer=setTimeout(()=>{if(stage!=='match'||token!==session)return;for(const n of [a,b]){const c=app.querySelector(`[data-card="${n}"]`);c.innerHTML='✦<span class="caption">Explore</span>';c.setAttribute('aria-label','Turn card '+(n+1));}opened=[];busy=false;},1600);}}
function show(){if(stage==='match'){clearTimeout(matchTimer);matched=new Set([0,1,2,3,4,5]);opened=[];busy=false;solved[0]=true;render();status('The moons are cards 1 and 5; the stars are 2 and 4; the suns are 3 and 6. Seeing a connection is a way to learn it.');}if(stage==='pattern'){unlock(1,'The star comes next: moon, star, moon, star. You can use what repeats to find your way.');app.querySelector('[data-answer="star"]').setAttribute('aria-pressed','true');}if(stage==='align'){angles=[0,0,0];solved[2]=true;render();status('The diamonds meet the stars at the top. Asking for guidance can help you see what to try next.');}}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
if(b.dataset.action){const a=b.dataset.action;if(a==='listen'){if(!voice.paused){voice.pause();narration=false;updateSound();return;}narration=true;updateSound();play();return;}if(a==='hint'){status(stage==='match'?'Look for the same symbol. The moon is behind cards 1 and 5.':stage==='pattern'?'Read the first two shapes as a pair: moon, star. That pair repeats.':'Start with dial 3: one tap will move its diamond to the top. Keep turning each remaining dial until it reaches its star.');return;}if(a==='show'){show();return;}if(a==='restart'){found=new Set();matched=new Set();chosen=[];solved=[false,false,false];angles=[90,180,270];go('intro');return;}go(a);return;}
if(b.dataset.light!==undefined){const i=Number(b.dataset.light);found.add(i);b.classList.add('found');document.querySelector('#discovery').innerHTML='<h3>'+messages[i][0]+'</h3><p>'+messages[i][1]+'</p>';return;}
if(b.dataset.card!==undefined){turnCard(Number(b.dataset.card));return;}
if(b.dataset.answer){if(solved[1])return;if(b.dataset.answer==='star'){b.setAttribute('aria-pressed','true');unlock(1,'Moon, star. Moon, star. You noticed the rhythm, one piece at a time.');}else status('Look at the first two shapes together. You can try another one.');return;}
if(b.dataset.dial!==undefined){if(solved[2])return;const i=Number(b.dataset.dial);angles[i]+=90;document.querySelector('#pointer'+i).style.transform=`rotate(${angles[i]}deg)`;document.querySelector('#dialstate'+i).textContent=angles[i]%360===0?'In focus':'Keep exploring';if(angles.every(a=>a%360===0))unlock(2,'There it is. A little adjustment, another look, and things become clearer.');return;}
if(b.dataset.word){const w=b.dataset.word;if(chosen.includes(w))chosen=chosen.filter(x=>x!==w);else if(chosen.length<5)chosen.push(w);else{status('Five lights fill this little sky. Tap a chosen light to swap it.');return;}render();app.querySelector(`[data-word="${w}"]`).focus({preventScroll:true});}
});
for(let i=0;i<65;i++){const s=document.createElement('i');s.className='dust';s.style.cssText=`left:${(i*47.3)%100}%;top:${(i*31.7)%100}%;animation-delay:-${i%7}s;animation-duration:${3+i%5}s`;document.querySelector('#stardust').append(s);}render();
})();
