'use strict';
const $=id=>document.getElementById(id),content=$('content'),garden=$('garden'),audio=$('narration');
let stage=0,voiceOn=true,voiceText={},memory='',intention='',care=0,selected='',timer=null,remaining=120,running=false,deadline=0,activeClip='';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const say=s=>{$('live').textContent=s;};
const snippets={'Too much to do':'You can choose an order. Only the next small piece needs your attention now.','What if I forget?':'You can practise recalling one small piece, then check your notes and build from there.','I don’t know where to begin':'We will choose one clear place to start together.'};
const choices=(list,kind)=>`<div class="choices">${list.map(s=>`<button class="choice" data-kind="${kind}" data-value="${esc(s)}" aria-pressed="false">${esc(s)}</button>`).join('')}</div>`;
const heading=(eyebrow,title,copy)=>`<p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="intro">${copy}</p>`;
function show(html,clip){content.innerHTML=html;content.style.animation='none';requestAnimationFrame(()=>content.style.animation='');garden.dataset.stage=stage;document.querySelectorAll('.progress span').forEach((e,i)=>e.classList.toggle('active',i===Math.min(stage,4)));$('read-along').open=false;if(stage>0&&clip){$('voice-bar').hidden=false;$('read-along').hidden=false;playMessage(clip);}else{audio.pause();activeClip='';$('voice-bar').hidden=true;$('read-along').hidden=true;}content.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>selectChoice(b));const h=content.querySelector('h1');if(stage>0){h.setAttribute('tabindex','-1');h.focus({preventScroll:true});}say(h.textContent);}
function selectChoice(b){selected=b.dataset.value;content.querySelectorAll('.choice').forEach(x=>{const on=x===b;x.classList.toggle('selected',on);x.setAttribute('aria-pressed',on);});if($('own'))$('own').value='';if($('response'))$('response').textContent=snippets[selected]||'';if($('continue'))$('continue').disabled=false;}
function ownField(label,placeholder){return `<label for="own">${label}</label><input id="own" maxlength="140" placeholder="${placeholder}" autocomplete="off">`;}
function bindOwn(){const field=$('own');if(field)field.oninput=()=>{selected='';content.querySelectorAll('.choice').forEach(x=>{x.classList.remove('selected');x.setAttribute('aria-pressed','false');});$('continue').disabled=!field.value.trim();if($('response'))$('response').textContent='';};}
function inputValue(){return $('own')?.value.trim()||selected;}
function render(){selected='';
 if(stage===0){show(heading('A FEW GENTLE MOMENTS, JUST FOR YOU','A little garden,<br><em>grown by you.</em>','Come in, Hind. Set something down, remember your strength, and give one small beginning a little care.')+`<p class="love-note">“My love, today we’ll grow a little reminder of what you can do.”</p><button class="primary" id="begin">Grow my little garden</button><p class="small">Go at your own pace. You can listen or read.</p>`);$('begin').onclick=()=>{stage=1;render();};return;}
 if(stage===1){show(heading('01 · MAKE A LITTLE ROOM','What can you<br><em>set down for a moment?</em>','Choose a thought to place on the stone beside your pot.')+choices(Object.keys(snippets),'worry')+ownField('Or use your own words','A few words, if you want…')+`<p class="response" id="response" aria-live="polite"></p><button id="continue" class="primary" disabled>Set it beside the path</button><button class="secondary" id="skip">I’ll keep my thought to myself</button>`,'setdown');bindOwn();$('continue').onclick=setDown;$('skip').onclick=setDown;return;}
 if(stage===2){show(heading('02 · FIND YOUR ROOTS','You have<br><em>learned before.</em>','Remember something that once felt difficult and became more familiar. Small examples count.')+choices(['A topic I practised','A task I learned','Something I understood after asking'],'memory')+ownField('Or name your own example','I learned how to…')+`<button id="continue" class="primary" disabled>Plant this reminder</button><button class="secondary" id="skip">I have a memory in mind</button>`,'remember');bindOwn();$('continue').onclick=()=>{memory=inputValue();plantSeed();};$('skip').onclick=()=>{memory='I have learned before. I can learn again.';plantSeed();};return;}
 if(stage===3){show(heading('03 · GIVE YOURSELF SOME CARE','Let a little<br><em>care reach you, too.</em>','Take each moment at your own pace. Water your plant whenever you’re ready.')+`<div class="care-orbit" aria-hidden="true"><span>gently</span></div><div id="care-label" class="care-label" aria-live="polite"></div><button class="primary" id="water-button"></button><button class="secondary" id="skip-care">I’d like to continue</button>`,'care');setCare();$('water-button').onclick=water;$('skip-care').onclick=()=>{care=3;garden.classList.add('watered','care-2','care-3');stage=4;render();};return;}
 if(stage===4){show(heading('04 · CHOOSE YOUR BEGINNING','One small step.<br><em>One place to start.</em>','Choose something manageable to carry back into your day.')+choices(['Understand one paragraph','Try one question','Ask for one explanation','Take a short break, then return'],'intention')+ownField('Or plant your own intention','My next small step is…')+`<button id="continue" class="primary" disabled>Let my intention bloom</button>`,'intention');bindOwn();$('continue').onclick=()=>{intention=inputValue();garden.classList.add('bloomed','care-3');$('plant-description').textContent='Your golden flower is blooming above three green leaves';$('garden-caption').textContent='You can give your next step the same care.';stage=5;render();};return;}
 if(stage===5){show(heading('YOUR FIRST FLOWER','Look what you<br><em>helped grow.</em>','Keep this little reminder close, my love.')+`<div class="letter"><p class="eyebrow">FOR YOU, HIND</p><p>You remembered your ability to learn, gave yourself some care, and chose where to begin.</p><div class="keepsake"><span>YOUR ROOTS</span><p>${esc(memory)}</p></div><div class="keepsake"><span>YOUR NEXT SMALL STEP</span><p>${esc(intention)}</p></div><p>May Allah calm your heart, make your learning clear, bless your effort, and grant you success. Ameen.</p><p class="signature">I believe in you. With love, Musfiqur</p></div><button class="primary" id="focus">Spend two gentle minutes with my step</button><button class="secondary" id="carry">I’ll take my step from here</button>`,'bloom');$('focus').onclick=focusView;$('carry').onclick=()=>finish(false);return;}}
function setDown(){garden.classList.add('stone-away');$('garden-caption').textContent='For these few moments, you can set it down.';stage=2;render();}
function plantSeed(){garden.classList.add('planted');$('plant-description').textContent='A golden seed planted in your pot';$('garden-caption').textContent='I have learned before. I can learn again.';stage=3;render();}
const carePrompts=[['Let your shoulders settle','Soften your hands, if that feels comfortable.','I’m ready · give a little water'],['Notice something around you','Look away and find one colour, object, or patch of light.','I noticed something · water again'],['Take a comfortable breath','Breathe naturally. There is nothing to count.','One more little drink']];
function setCare(){if(care>0)playMessage('care'+(care+1));const p=carePrompts[Math.min(care,2)];$('care-label').innerHTML=`<b>${p[0]}</b><small>${p[1]}</small>`;$('water-button').textContent=p[2];}
function water(){const button=$('water-button');button.disabled=true;garden.classList.remove('pouring');requestAnimationFrame(()=>garden.classList.add('pouring'));care++;garden.classList.add('watered');if(care>1)garden.classList.add('care-2');if(care>2)garden.classList.add('care-3');$('plant-description').textContent=`Your plant has grown ${care} green ${care===1?'leaf':'leaves'}`;$('garden-caption').textContent=['A little care is a beginning.','You can make room for yourself.','You can grow at your own pace.'][care-1];setTimeout(()=>{garden.classList.remove('pouring');if(stage!==3)return;if(care>=3){stage=4;render();}else{setCare();button.disabled=false;}},1200);}
function focusView(){audio.pause();remaining=120;running=false;clearInterval(timer);show(heading('YOUR OWN SMALL BEGINNING','Take your time,<br><em>my love.</em>','Give your chosen step a little attention. You can pause or finish whenever you need.')+`<p class="love-note">${esc(intention)}</p><div class="clock" id="clock" role="timer" aria-label="Two minutes remaining">2:00</div><p class="small" style="text-align:center">Your flower stays. This is simply time for you.</p><div class="timer-actions"><button id="timer-button">Begin my two minutes</button><button id="finish-step">I’ve given my step some attention</button></div><button class="secondary" id="back-letter">Back to my flower</button>`);$('timer-button').onclick=toggleTimer;$('finish-step').onclick=()=>finish(true);$('back-letter').onclick=()=>{clearInterval(timer);running=false;render();};}
function updateClock(){if(running)remaining=Math.max(0,(deadline-Date.now())/1000);const el=$('clock');if(!el)return;const seconds=Math.ceil(remaining);el.textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;el.setAttribute('aria-label',`${seconds} seconds remaining`);if(remaining<=0){clearInterval(timer);running=false;$('timer-button').disabled=true;$('timer-button').textContent='Two minutes, gently given';$('finish-step').textContent='Reflect on my small step';say('Your two minutes are complete. Take your time finishing.');}}
function toggleTimer(){if(running){updateClock();running=false;clearInterval(timer);$('timer-button').textContent='Continue my time';}else{running=true;deadline=Date.now()+remaining*1000;$('timer-button').textContent='Pause my time';timer=setInterval(updateClock,250);}updateClock();}
function finish(didStep){clearInterval(timer);running=false;stage=6;show(heading(didStep?'A MOMENT TO RECOGNISE':'CARRY YOUR GARDEN WITH YOU',didStep?'You gave yourself<br><em>a beginning.</em>':'Your next step<br><em>is waiting gently.</em>',didStep?'Notice one thing you understood, tried, or want to ask next. You can build from there.':'Take your intention into your day whenever you are ready.')+`<p class="love-note">“Hind, keep giving yourself the patience and the chance to learn. I believe in you.”</p><div class="keepsake"><span>MY NEXT SMALL STEP</span><p>${esc(intention)}</p></div><p class="finished-line">I am capable.<br>I can learn this.<br>I can take the next step.</p><p class="intro">Bismillah, my love. One step at a time.</p><button class="primary" id="return-flower">Sit with my flower a little longer</button><a class="secondary" style="text-align:center" href="../day-2/">Return to your rooms of encouragement</a>`,didStep?'finish':'bloom');$('return-flower').onclick=()=>{stage=5;render();};}
async function playMessage(key){audio.pause();activeClip=key;$('audio-status').textContent='';$('pause').textContent='Pause';$('transcript').textContent=voiceText[key]||'Your message is loading…';audio.src=`assets/${key}.mp3`;if(voiceOn){try{await audio.play();}catch{if(activeClip===key)$('audio-status').textContent='Tap Hear this message to listen.';}}}
function syncSound(){ $('sound').textContent=voiceOn?'Voice on':'Voice off';$('sound').setAttribute('aria-pressed',String(voiceOn));$('sound').setAttribute('aria-label',voiceOn?'Turn narration off':'Turn narration on');}
$('sound').onclick=()=>{voiceOn=!voiceOn;syncSound();if(!voiceOn)audio.pause();else if(activeClip)audio.play().catch(()=>{$('audio-status').textContent='Tap Hear this message to listen.';});};
$('replay').onclick=()=>{voiceOn=true;syncSound();audio.currentTime=0;if(audio.error)audio.load();audio.play().catch(()=>{$('audio-status').textContent='Audio is unavailable. You can read the whole message below.';});};$('pause').onclick=()=>{if(audio.paused){voiceOn=true;syncSound();audio.play().catch(()=>{});}else audio.pause();};
audio.addEventListener('playing',()=>{$('pause').textContent='Pause';$('audio-status').textContent='';});audio.addEventListener('pause',()=>{$('pause').textContent='Continue';});audio.addEventListener('ended',()=>{$('pause').textContent='Replay';});audio.addEventListener('error',()=>{$('audio-status').textContent='You can read the message below while audio is unavailable.';});document.addEventListener('visibilitychange',()=>{if(document.hidden)audio.pause();});
fetch('script.json?v=1').then(r=>{if(!r.ok)throw Error('message');return r.json();}).then(data=>{voiceText=data;if(activeClip)$('transcript').textContent=voiceText[activeClip]||'';}).catch(()=>{$('transcript').textContent='My beloved Hind, I believe in your ability to learn. Give yourself patience and take one small step. May Allah calm your heart, bless your effort, and grant you success. Ameen. With love, Musfiqur.';});
const ns='http://www.w3.org/2000/svg';for(let i=0;i<12;i++){const p=document.createElementNS(ns,'ellipse');p.setAttribute('cx','0');p.setAttribute('cy','-31');p.setAttribute('rx','14');p.setAttribute('ry','30');p.setAttribute('fill','url(#petal)');p.setAttribute('transform',`rotate(${i*30})`);$('petals').appendChild(p);}for(let i=0;i<18;i++){const light=document.createElement('i');light.style.left=(10+Math.random()*80)+'%';light.style.top=(10+Math.random()*80)+'%';light.style.animationDelay=(Math.random()*9)+'s';document.querySelector('.glimmers').appendChild(light);}render();
